### ISSUE TITLE
「快捷键」界面与集成编辑环境插件冲突，无法显示

### ISSUE THREAD

**Issue by TCOTC** [Zuoqiu-Yingyi/siyuan-plugin-monaco-editor#28]
安装了 [v3.0.5-dev1](https://github.com/siyuan-note/siyuan/releases/tag/v3.0.5-dev1) ，发现「快捷键」界面与集成编辑环境插件冲突，无法显示。

只要打开这两个选项的其中一个：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3a1fc754-3db0-40d1-a21e-8863dec0f604)

就会导致「快捷键」界面一片空白：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/caa6ea74-f2f9-470b-bd79-dbcdf39547fa)

同时控制台会产生一条报错：

```
main.f60697176fa84716dbb1.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at J (main.f60697176fa84716dbb1.js:9:4468)
    at main.f60697176fa84716dbb1.js:4682:122
    at Array.forEach (<anonymous>)
    at main.f60697176fa84716dbb1.js:4682:34
    at Array.forEach (<anonymous>)
    at Object.genHTML (main.f60697176fa84716dbb1.js:4672:54)
    at iw (main.f60697176fa84716dbb1.js:6211:1368)
    at HTMLLIElement.<anonymous> (main.f60697176fa84716dbb1.js:6250:727)
J @ main.f60697176fa84716dbb1.js:9
（匿名） @ main.f60697176fa84716dbb1.js:4682
（匿名） @ main.f60697176fa84716dbb1.js:4682
genHTML @ main.f60697176fa84716dbb1.js:4672
iw @ main.f60697176fa84716dbb1.js:6211
（匿名） @ main.f60697176fa84716dbb1.js:6250
```

是从 v3.0.5-dev1 开始才出现这个问题的，不确定是思源还是插件的问题

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/10682

**Comment by TCOTC** [comment]
思源的问题，已经解决了
